# NOTE::
#
# The services, settings and environment setup in this compose file is
# for DEVELOPMENT ONLY!
#
# Do not use this compose file in a live environment.

networks:
  dmptool-network:
    driver: bridge

services:
  db:
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql/mysql-server:latest
    ports:
      - "3308:3306"
      - "3306:3306"
    expose:
      - "3308"
    networks:
      - dmptool-network
    environment:
      MYSQL_DATABASE: 'dmp'
      MYSQL_ROOT_PASSWORD: 'dockerSecret'
      MYSQL_USER: 'dmpuser'
      MYSQL_PASSWORD: 'abcdefghij'
    volumes:
      - "./docker/mysql:/var/lib/mysql"

  dmptool:
    container_name: dmptool
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f ./tmp/pids/server.pid && rm -f ./tmp/pids/delayed_job.pid && ./bin/dev"
    user: "1000:1000"
    links:
      - db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - dmptool-network
    environment:
      - RAILS_ENV=development
      - DMPROADMAP_DATABASE_HOST=mysql
      - DMPROADMAP_DATABASE_PORT=3306
      - DMPROADMAP_DATABASE_USERNAME=dmpuser
      - DMPROADMAP_DATABASE_PASSWORD=abcdefghij
      - DMPROADMAP_DATABASE_NAME=dmp
      # The first time you startup these docker containers, you will need to uncomment the
      # following FIRST_TIME variable so the MySQL database is properly initialized.
      #
      # - FIRST_TIME=true
    env_file:
      - .env.dev
    volumes:
      - ./:/opt/app
